export const profileFormController = ({
  genderOp,
  stateOp,
  zipCodeOp,
}) => [
  {
    name: "name",
    type: "input",
    inputType: "text",
    placeholder: "Full Name",
    label: "Full Name",
    isRequired: "Name is required",
  },
  {
    name: "username",
    type: "input",
    inputType: "text",
    placeholder: "User Name",
    label: "User Name",
    disableTyping: true,
  },
  {
    name: "email",
    type: "input",
    inputType: "email",
    placeholder: "Email",
    label: "Email",
    disableTyping: true,
  },
  {
    name: "phone",
    type: "input",
    inputType: "text",
    placeholder: "Phone Number",
    label: "Phone Number",
  },
  {
    name: "gender",
    type: "select",
    placeholder: "Gender",
    label: "Gender",
    options: genderOp,
  },
  {
    name: "dob",
    type: "input",
    inputType: "date",
    placeholder: "Date of Birth",
    label: "Date of Birth",
  },
  {
    name: "address",
    type: "input",
    inputType: "text",
    placeholder: "Address",
    label: "Address",
  },
  {
    name: "state",
    type: "select",
    placeholder: "Select State",
    label: "State",
    options: stateOp,
  },
  {
    name: "zipcode",
    type: "select",
    placeholder: "Select Zip Code",
    label: "Zip Code",
    options: zipCodeOp,
  },
];
