export const PROFILE_FORM_CONTROLLER = [
  {
    name: "name",
    type: "input",
    inputType: "text",
    placeholder: "Full Name",
    isRequired: "Name is required",
    style: {
      padding: "10px",
      borderRadius: "8px",
      border: "1px solid #3f3f40",
      fontSize: "14px",
      width: "94%",
    },
  },
  {
    name: "username",
    type: "input",
    inputType: "text",
    placeholder: "User Name",
    isRequired: "Username is required",
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "8px",
      border: "1px solid #3f3f40",
      fontSize: "14px",
      width: "94%",
    },
  },
  {
    name: "email",
    type: "input",
    inputType: "email",
    placeholder: "Email",
    isRequired: "Email is required",
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "8px",
      border: "1px solid #3f3f40",
      fontSize: "14px",
      width: "94%",
    },
  },
  {
    name: "phone",
    type: "input",
    inputType: "text",
    placeholder: "Phone Number",
    isRequired: false,
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "8px",
      border: "1px solid #3f3f40",
      fontSize: "14px",
      width: "94%",
    },
  },
  {
    name: "gender",
    type: "select",
    placeholder: "Gender",
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
      { label: "Other", value: "other" },
    ],
    isRequired: false,
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "8px",
      border: "1px solid #3f3f40",
      fontSize: "14px",
      width: "100%",
    },
  },
  {
    name: "dob",
    type: "input",
    inputType: "date",
    placeholder: "Date of Birth",
    isRequired: false,
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "8px",
      border: "1px solid #3f3f40",
      fontSize: "14px",
      width: "94%",
    },
  },
  {
    name: "address",
    type: "input",
    inputType: "text",
    placeholder: "Address",
    isRequired: false,
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "6px",
      border: "1px solid #3f3f40",
      fontSize: "14px",
      width: "94%",
    },
  },
  {
    name: "state",
    type: "select",
    placeholder: "Select State",
    options: [
      { label: "Madhya Pradesh", value: "MP" },
      { label: "Maharashtra", value: "MH" },
      { label: "Delhi", value: "DL" },
      { label: "Uttar Pradesh", value: "UP" },
      { label: "Rajasthan", value: "RJ" },
    ],
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "6px",
      border: "1px solid #3f3f40",
      width: "100%",
    },
  },
  {
    name: "zipcode",
    type: "select",
    placeholder: "Select Zip Code",
    options: [
      { label: "452001", value: "452001" },
      { label: "452002", value: "452002" },
      { label: "452003", value: "452003" },
      { label: "452004", value: "452004" },
    ],
    style: {
      marginTop: "10px",
      padding: "10px",
      borderRadius: "6px",
      border: "1px solid #3f3f40",
      width: "100%",
    },
  },
];
